# Generated by Django 4.0.1 on 2022-08-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
